version: "3.8"
services:
  app:
    build: .
    image: setra-cheating:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./:/app   # optional for live editing in dev; remove in prod